/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void DIFF_EQ_changed(GTextField source, GEvent event) { //_CODE_:DIFF_EQ:858581:
    timePause = true;
    println(source);
    resetLevel();
    DiffEQ = source.getText();
    generateSlopeField(DiffEQ, a, b);
} //_CODE_:DIFF_EQ:858581:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:528910:
  //a = (float) Math.pow(source.getValueF(), 3.0);
  if (a>99) a=100.00;
  if (a<-99) a=-100.00;
  timePause = true;
  resetLevel();
  generateSlopeField(DiffEQ, a, b);
} //_CODE_:slider1:528910:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:623745:
  //b = (float) Math.pow(source.getValueF(), 3.0);
  if (b>99) b=100.00;
  if (b<-99) b=-100.00;
  timePause = true;
  resetLevel();
  generateSlopeField(DiffEQ, a, b);
} //_CODE_:slider2:623745:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  DIFF_EQ = new GTextField(this, 100, 815, 600, 30, G4P.SCROLLBARS_NONE);
  DIFF_EQ.setPromptText("Enter Differential Equation");
  DIFF_EQ.setLocalColorScheme(GCScheme.RED_SCHEME);
  DIFF_EQ.setOpaque(false);
  DIFF_EQ.addEventHandler(this, "DIFF_EQ_changed");
  slider1 = new GSlider(this, 100, 850, 290, 40, 10.0);
  slider1.setLimits(0.0, -4.6415887, 4.6415887);
  slider1.setNbrTicks(999);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  slider2 = new GSlider(this, 410, 850, 290, 40, 10.0);
  slider2.setLimits(0.0, -4.6415887, 4.6415887);
  slider2.setNbrTicks(999);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
}

// Variable declarations 
// autogenerated do not edit
GTextField DIFF_EQ; 
GSlider slider1; 
GSlider slider2; 
